--------------------------------------------------------
--  File created - Wednesday-May-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "WASSIM"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "WASSIM"."COMMANDES" 
   (	"ID_COM" NUMBER, 
	"TYPE_COM" VARCHAR2(20 BYTE), 
	"DATE_COM" DATE, 
	"ID_STAFF" NUMBER, 
	"ID_CLIENT" NUMBER, 
	"ID_PLAT" NUMBER, 
	"ID_TABLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "WASSIM"."CONGE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMEMPLOYE" VARCHAR2(20 BYTE), 
	"DATED" VARCHAR2(20 BYTE), 
	"DATEF" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONNEXIONU
--------------------------------------------------------

  CREATE TABLE "WASSIM"."CONNEXIONU" 
   (	"USERN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENTS
--------------------------------------------------------

  CREATE TABLE "WASSIM"."EVENEMENTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"DA" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "WASSIM"."FOURNISSEUR" 
   (	"ID_F" VARCHAR2(20 BYTE), 
	"NOM_F" VARCHAR2(20 BYTE), 
	"TYPE_F" VARCHAR2(20 BYTE), 
	"NUM_F" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "WASSIM"."LIVRAISON" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DATEE" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFRES
--------------------------------------------------------

  CREATE TABLE "WASSIM"."OFFRES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANNING
--------------------------------------------------------

  CREATE TABLE "WASSIM"."PLANNING" 
   (	"ID_PRESENCE" VARCHAR2(20 BYTE), 
	"DATE_PRESENCE" DATE, 
	"NB_HEURE" NUMBER, 
	"STAFF" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLATS
--------------------------------------------------------

  CREATE TABLE "WASSIM"."PLATS" 
   (	"ID_PLAT" NUMBER, 
	"NOM_PLAT" VARCHAR2(20 BYTE), 
	"DESCRIPTION_PLAT" VARCHAR2(20 BYTE), 
	"PRIX_PLAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "WASSIM"."PRODUIT" 
   (	"ID_P" VARCHAR2(20 BYTE), 
	"TYPE_P" VARCHAR2(20 BYTE), 
	"DESC_P" VARCHAR2(20 BYTE), 
	"QUANTITE_P" VARCHAR2(20 BYTE), 
	"PRIX_P" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "WASSIM"."RESERVATION" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"Nom" VARCHAR2(20 BYTE), 
	"Prenom" VARCHAR2(20 BYTE), 
	"Mail" VARCHAR2(20 BYTE), 
	"Tel" VARCHAR2(20 BYTE), 
	"Dat" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "WASSIM"."STAFF" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"TELEPHONE" VARCHAR2(8 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(30 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLES
--------------------------------------------------------

  CREATE TABLE "WASSIM"."TABLES" 
   (	"ETAT" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WASSIM.CLIENT
SET DEFINE OFF;
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('333','hhhh','yyyyy','7777','JJJJJ','NNNNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('test','test','3','testBBB','AAAA','test');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('11','HHHHH','33','55555','55','66');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('BBB','BBB','NNN','JJJ','LLLL','NNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('444','KKK','yyyyy','7777','JJJJJ','NNNNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('88','testttt','testtt','852','ddgggs','jjjjjj');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('ggggv','bbb','nnn','kkkl','UUUU','jjjj');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('333','hhhh','yyyyy','7777','JJJJJ','NNNNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('test','test','3','testBBB','AAAA','test');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('11','HHHHH','33','55555','55','66');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('BBB','BBB','NNN','JJJ','LLLL','NNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('444','KKK','yyyyy','7777','JJJJJ','NNNNNN');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('88','testttt','testtt','852','ddgggs','jjjjjj');
Insert into WASSIM.CLIENT (ID,NOM,PRENOM,NUM,MAIL,ADRESS) values ('ggggv','bbb','nnn','kkkl','UUUU','jjjj');
REM INSERTING into WASSIM.COMMANDES
SET DEFINE OFF;
Insert into WASSIM.COMMANDES (ID_COM,TYPE_COM,DATE_COM,ID_STAFF,ID_CLIENT,ID_PLAT,ID_TABLE) values (4,'sur place',to_date('16-MAR-21','DD-MON-RR'),10,11,1,3);
Insert into WASSIM.COMMANDES (ID_COM,TYPE_COM,DATE_COM,ID_STAFF,ID_CLIENT,ID_PLAT,ID_TABLE) values (5,'sur place',to_date('01-JAN-00','DD-MON-RR'),null,null,null,null);
REM INSERTING into WASSIM.CONGE
SET DEFINE OFF;
Insert into WASSIM.CONGE (ID,NOMEMPLOYE,DATED,DATEF,TYPE) values ('1','wassim','Wed Apr 14 2021','Wed May 5 2021',' CONGEE ANNUEL');
Insert into WASSIM.CONGE (ID,NOMEMPLOYE,DATED,DATEF,TYPE) values ('2','jesser','Wed Apr 14 2021','Thu May 20 2021','CONGEE PAYEE');
REM INSERTING into WASSIM.CONNEXIONU
SET DEFINE OFF;
Insert into WASSIM.CONNEXIONU (USERN,MDP) values ('admin','admin');
REM INSERTING into WASSIM.EVENEMENTS
SET DEFINE OFF;
Insert into WASSIM.EVENEMENTS (ID,NOM,PRIX,DA,DESCRIPTION) values ('564557','moh','65','Sat Jan 1 2000','tretergdgf');
Insert into WASSIM.EVENEMENTS (ID,NOM,PRIX,DA,DESCRIPTION) values ('0','bbbbb','4.534E+003','Thu Jan 1 1998','ghfghfghf');
Insert into WASSIM.EVENEMENTS (ID,NOM,PRIX,DA,DESCRIPTION) values ('656747','hhhh','45','Thu Jan 1 1998','ghfghfghf');
REM INSERTING into WASSIM.FOURNISSEUR
SET DEFINE OFF;
Insert into WASSIM.FOURNISSEUR (ID_F,NOM_F,TYPE_F,NUM_F) values ('1','delice','lait','71937483');
Insert into WASSIM.FOURNISSEUR (ID_F,NOM_F,TYPE_F,NUM_F) values ('12334','az','fcfe','dez');
Insert into WASSIM.FOURNISSEUR (ID_F,NOM_F,TYPE_F,NUM_F) values ('12345432','df','sdf','ssss');
Insert into WASSIM.FOURNISSEUR (ID_F,NOM_F,TYPE_F,NUM_F) values ('111','YVGUBH','BHUN','56789');
REM INSERTING into WASSIM.LIVRAISON
SET DEFINE OFF;
Insert into WASSIM.LIVRAISON (ID,DATEE,LIEU,ETAT) values ('3333','145667','TUNIS','NON LIVRE');
Insert into WASSIM.LIVRAISON (ID,DATEE,LIEU,ETAT) values ('2354678','vb,v','vhv,','NON LIVRE');
REM INSERTING into WASSIM.OFFRES
SET DEFINE OFF;
Insert into WASSIM.OFFRES (ID,NOM,PRIX,DESCRIPTION) values ('1','ahmed','5.5E+001',null);
Insert into WASSIM.OFFRES (ID,NOM,PRIX,DESCRIPTION) values ('66','waazd','50',null);
REM INSERTING into WASSIM.PLANNING
SET DEFINE OFF;
Insert into WASSIM.PLANNING (ID_PRESENCE,DATE_PRESENCE,NB_HEURE,STAFF) values (null,to_date('01-JAN-00','DD-MON-RR'),5,'jesser');
REM INSERTING into WASSIM.PLATS
SET DEFINE OFF;
Insert into WASSIM.PLATS (ID_PLAT,NOM_PLAT,DESCRIPTION_PLAT,PRIX_PLAT) values (4,'pasta fruit de mer','st from fm',20);
Insert into WASSIM.PLATS (ID_PLAT,NOM_PLAT,DESCRIPTION_PLAT,PRIX_PLAT) values (1,'pizza neptune','st from thon',12);
Insert into WASSIM.PLATS (ID_PLAT,NOM_PLAT,DESCRIPTION_PLAT,PRIX_PLAT) values (2,'pizza vegetarienne','st from legumes',13);
Insert into WASSIM.PLATS (ID_PLAT,NOM_PLAT,DESCRIPTION_PLAT,PRIX_PLAT) values (3,'pizza fruit de mer','st from fm',18);
REM INSERTING into WASSIM.PRODUIT
SET DEFINE OFF;
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('456','IHBNJ','GVU','UHB','345');
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('69','Lait','hjih','hhj','33566');
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('1','koi','guvbh','bhun',' bh');
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('2','Lait','lait bnin','30','3');
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('13','322','FFES','23','232');
Insert into WASSIM.PRODUIT (ID_P,TYPE_P,DESC_P,QUANTITE_P,PRIX_P) values ('12','fff','sdsd','sdsd','dsds');
REM INSERTING into WASSIM.RESERVATION
SET DEFINE OFF;
Insert into WASSIM.RESERVATION (CIN,"Nom","Prenom","Mail","Tel","Dat") values ('1','behija','bahouja','hcx@gb.fdx','253698741',to_date('21-MAY-00','DD-MON-RR'));
REM INSERTING into WASSIM.STAFF
SET DEFINE OFF;
Insert into WASSIM.STAFF (CIN,NOM,PRENOM,EMAIL,TELEPHONE,LOGIN,PASSWORD,ROLE,SALAIRE) values ('09941060','wassim','benromdhane','wassimbenr@gmail.com','94366666','wassim','wassim','Serveur',1200);
Insert into WASSIM.STAFF (CIN,NOM,PRENOM,EMAIL,TELEPHONE,LOGIN,PASSWORD,ROLE,SALAIRE) values ('09946010','Dhia','Abdeli','dhiaabdeli@esprit.tn','94368226','dhia','dhia','livreur',300);
REM INSERTING into WASSIM.TABLES
SET DEFINE OFF;
Insert into WASSIM.TABLES (ETAT,NUMERO) values ('reserve','1');
Insert into WASSIM.TABLES (ETAT,NUMERO) values ('reserve','66');
Insert into WASSIM.TABLES (ETAT,NUMERO) values ('vide','55');
--------------------------------------------------------
--  DDL for Index PLATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."PLATS_PK" ON "WASSIM"."PLATS" ("ID_PLAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."STAFF_PK" ON "WASSIM"."STAFF" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."CONGE_PK" ON "WASSIM"."CONGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVRAISON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."LIVRAISON_PK" ON "WASSIM"."LIVRAISON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."EVENEMENTS_PK" ON "WASSIM"."EVENEMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."PRODUIT_PK" ON "WASSIM"."PRODUIT" ("ID_P") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."CLIENT_PK" ON "WASSIM"."RESERVATION" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."COMMANDES_PK" ON "WASSIM"."COMMANDES" ("ID_COM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."OFFRES_PK" ON "WASSIM"."OFFRES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."FOURNISSEUR_PK" ON "WASSIM"."FOURNISSEUR" ("ID_F") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PLATS
--------------------------------------------------------

  ALTER TABLE "WASSIM"."PLATS" MODIFY ("ID_PLAT" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PLATS" ADD CONSTRAINT "PLATS_PK" PRIMARY KEY ("ID_PLAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFFRES
--------------------------------------------------------

  ALTER TABLE "WASSIM"."OFFRES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."OFFRES" ADD CONSTRAINT "OFFRES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "WASSIM"."LIVRAISON" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."LIVRAISON" ADD CONSTRAINT "LIVRAISON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "WASSIM"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENTS
--------------------------------------------------------

  ALTER TABLE "WASSIM"."EVENEMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."EVENEMENTS" ADD CONSTRAINT "EVENEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "WASSIM"."RESERVATION" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."RESERVATION" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANNING
--------------------------------------------------------

  ALTER TABLE "WASSIM"."PLANNING" MODIFY ("STAFF" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PLANNING" MODIFY ("NB_HEURE" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PLANNING" MODIFY ("DATE_PRESENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "WASSIM"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASSIM"."CONGE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."CONGE" MODIFY ("DATEF" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."CONGE" MODIFY ("DATED" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."CONGE" MODIFY ("NOMEMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."CONGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "WASSIM"."COMMANDES" MODIFY ("ID_COM" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."COMMANDES" ADD CONSTRAINT "COMMANDES_PK" PRIMARY KEY ("ID_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "WASSIM"."FOURNISSEUR" MODIFY ("ID_F" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."FOURNISSEUR" MODIFY ("NOM_F" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."FOURNISSEUR" MODIFY ("TYPE_F" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."FOURNISSEUR" MODIFY ("NUM_F" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID_F")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "WASSIM"."PRODUIT" MODIFY ("ID_P" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PRODUIT" MODIFY ("TYPE_P" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PRODUIT" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PRODUIT" MODIFY ("QUANTITE_P" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PRODUIT" MODIFY ("PRIX_P" NOT NULL ENABLE);
  ALTER TABLE "WASSIM"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "WASSIM"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASSIM"."STAFF" MODIFY ("CIN" NOT NULL ENABLE);
